### PR TITLE
Latest KVS repo fixes openssl issue

### PR DESCRIPTION
**Pull request by sauravkumar-volt**

### CODE REVIEW

**Comment by sauravkumar-volt** [comment]
Issue https://github.com/aws-samples/amazon-kinesis-video-streams-demos/issues/241

**Comment by sauravkumar-volt** [comment]
```
Factory Details:
  Rank                     primary + 10 (266)
  Long-name                KVS Plugin
  Klass                    Sink/Video/Network
  Description              GStreamer AWS KVS plugin
  Author                   AWS KVS <kinesis-video-support@amazon.com>

Plugin Details:
  Name                     kvsplugin
  Description              GStreamer AWS KVS plugin
  Filename                 /home/saurav/volt_ws/amazon-kinesis-video-streams-demos/gst/gst-kvs-plugin/build/libgstkvsplugin.so
  Version                  1.0
  License                  Proprietary
  Source module            kvspluginpackage
  Binary package           GStreamer
  Origin URL               http://gstreamer.net/

GObject
 +----GInitiallyUnowned
       +----GstObject
             +----GstElement
                   +----GstKvsPlugin

Pad Templates:
  SINK template: 'video_%u'
    Availability: On request
    Capabilities:
      video/x-h264
          stream-format: avc
              alignment: au
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
      video/x-h265
              alignment: au
                  width: [ 16, 2147483647 ]
                 height: [ 16, 2147483647 ]
  
  SINK template: 'audio_%u'
    Availability: On request
    Capabilities:
      audio/mpeg
            mpegversion: { (int)2, (int)4 }
          stream-format: raw
               channels: [ 1, 2147483647 ]
                   rate: [ 1, 2147483647 ]
      audio/x-alaw
               channels: { (int)1, (int)2 }
                   rate: [ 8000, 192000 ]
      audio/x-mulaw
               channels: { (int)1, (int)2 }
                   rate: [ 8000, 192000 ]
      audio/x-opus

Element has no clocking capabilities.
Element has no URI handling capabilities.

Pads:
  none

Element Properties:
  absolute-fragment-times: Use absolute fragment time
                        flags: readable, writable
                        Boolean. Default: true
  access-key          : AWS Access Key
                        flags: readable, writable
                        String. Default: "access_key"
  adapt-cpd-nals      : Adapt CPD NALs
                        flags: readable, writable
                        Boolean. Default: false
  adapt-frame-nals    : Adapt Frame NALs
                        flags: readable, writable
                        Boolean. Default: false
  avg-bandwidth-bps   : Average bandwidth bps
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 4194304 
  aws-region          : AWS Region
                        flags: readable, writable
                        String. Default: "us-west-2"
  buffer-duration     : Buffer duration. Unit: seconds
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 120 
  channel-name        : Name of the signaling channel
                        flags: readable, writable
                        String. Default: "DEFAULT_CHANNEL"
  codec-id            : Codec ID
                        flags: readable, writable
                        String. Default: "V_MPEG4/ISO/AVC"
  connect-webrtc      : Whether to connect to WebRTC signaling channel
                        flags: readable, writable
                        Boolean. Default: true
  connection-staleness: Connection staleness. Unit: seconds
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 4294967295 
  content-type        : content type
                        flags: readable, writable
                        String. Default: null
  credential-path     : Credential File Path
                        flags: readable, writable
                        String. Default: ".kvs/credential"
  disable-buffer-clipping: Set to true only if your src/mux elements produce GST_CLOCK_TIME_NONE for segment start times.  It is non-standard behavior to set this to true, only use if there are known issues with your src/mux segment start/stop times.
                        flags: readable, writable
                        Boolean. Default: false
  enable-streaming    : Whether to enable streaming frames to KVS
                        flags: readable, writable
                        Boolean. Default: true
  file-start-time     : Epoch time that the file starts in kinesis video stream. By default, current time is used. Unit: Seconds
                        flags: readable, writable
                        Unsigned Integer64. Range: 0 - 18446744073709551615 Default: 1654722655 
  fragment-acks       : Do fragment acks
                        flags: readable, writable
                        Boolean. Default: true
  fragment-duration   : Fragment Duration. Unit: miliseconds
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 2000 
  frame-timecodes     : Do frame timecodes
                        flags: readable, writable
                        Boolean. Default: true
  framerate           : Framerate
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 25 
  iot-certificate     : Use aws iot certificate to obtain credentials
                        flags: readable, writable
                        Boxed pointer of type "GstStructure"
  key-frame-fragmentation: If true, generate new fragment on each keyframe, otherwise generate new fragment on first keyframe after fragment-duration has passed.
                        flags: readable, writable
                        Boolean. Default: true
  log-level           : Logging Verbosity Level
                        flags: readable, writable
                        Unsigned Integer. Range: 1 - 8 Default: 4 
  log-path            : Specifying the directory where the file-based logger will store the files. 
                        flags: readable, writable
                        String. Default: ""
  max-latency         : Max Latency. Unit: seconds
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 4294967295 
  name                : The name of the object
                        flags: readable, writable
                        String. Default: "kvsplugin0"
  parent              : The parent of the object
                        flags: readable, writable
                        Object of type "GstObject"
  recalculate-metrics : Do recalculate metrics
                        flags: readable, writable
                        Boolean. Default: true
  replay-duration     : Replay duration. Unit: seconds
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 4294967295 
  restart-on-error    : Do restart on error
                        flags: readable, writable
                        Boolean. Default: true
  retention-period    : Length of time stream is preserved. Unit: hours
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 2 
  rotation-period     : Rotation Period. Unit: seconds
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 3600 
  secret-key          : AWS Secret Key
                        flags: readable, writable
                        String. Default: "secret_key"
  storage-size        : Storage Size. Unit: MB
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 128 
  stream-create-timeout: Stream create timeout. Unit: seconds
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 0 
  stream-name         : Name of the destination stream
                        flags: readable, writable
                        String. Default: "DEFAULT_STREAM"
  stream-stop-timeout : Stream stop timeout. Unit: seconds
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 0 
  stream-tags         : key-value pair that you can define and assign to each stream
                        flags: readable, writable
                        Boxed pointer of type "GstStructure"
  streaming-type      : KVS Producer streaming type
                        flags: readable, writable
                        Enum "STREAMING_TYPE" Default: 0, "realtime"
                           (0): realtime         - streaming type realtime
                           (1): near-realtime    - streaming type near realtime
                           (2): offline          - streaming type offline
  timecode-scale      : Timecode Scale. Unit: milliseconds
                        flags: readable, writable
                        Unsigned Integer. Range: 0 - 4294967295 Default: 1 
  trickle-ice         : Whether to use tricle ICE mode
                        flags: readable, writable
                        Boolean. Default: true
  webrtc-connection-mode: WebRTC connection mode - Default, Turn only, P2P only
                        flags: readable, writable
                        Enum "WEBRTC_CONNECTION_MODE" Default: 0, "default"
                           (0): default          - Default connection mode allowing both P2P and TURN
                           (1): turn             - TURN only connection mode
                           (2): p2p              - P2P only connection mode
```

**Comment by chenhudl** [comment]
Is this in process of merging to master?

**Comment by olivetom** [comment]
Would love to see this in master also! 
Marry Christmas to you @disa6302 @sauravkumar-volt

**Comment by mariobaldini** [comment]
Are you able to build this? 

I am able to build `libgstkvsplugin.so` but get `undefined symbol: signalingClientFetchSync` upon `gst-inspect-1.0 kvsplugin`

Tried building this PR unsuccessfully. 

Manually updating the CMakeLists FetchContent_Declare to:
``` 
GIT_REPOSITORY https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c
#GIT_TAG v1.7.3
GIT_TAG ced19d02ed6fbc1e59dd63bc19d847c5ec5ebf47

GIT_REPOSITORY https://github.com/awslabs/amazon-kinesis-video-streams-producer-c
#GIT_TAG v1.4.0
GIT_TAG 1204f14081caf300b4e9bbb93e0a8824cb67cd22
```


Breaks the build: 
```
[ 46%] Linking C shared library libkvsWebrtcSignalingClient.so
/usr/bin/ld: cannot find -lkvsCommonLws
collect2: error: ld returned 1 exit status
make[2]: *** [_deps/webrtc-build/CMakeFiles/kvsWebrtcSignalingClient.dir/build.make:181: _deps/webrtc-build/libkvsWebrtcSignalingClient.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:229: _deps/webrtc-build/CMakeFiles/kvsWebrtcSignalingClient.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

not sure how to trigger the build for this missing lib;
or if the error is on something else. 

My goal is to build `kvsplugin` to stream to kvs webrtc directly from a gtreamer pipeline
https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/gst/gst-kvs-plugin

**Comment by sauravkumar-volt** [comment]
Closing with [280](https://github.com/aws-samples/amazon-kinesis-video-streams-demos/pull/280)

**Pull request closed without merging**
